# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/dream-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000030.tlbin:system/app/mcRegistry/ffffffff000000000000000000000030.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000038.tlbin:system/app/mcRegistry/ffffffff000000000000000000000038.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff00000000000000000000003e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000003e.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000047.tlbin:system/app/mcRegistry/ffffffff000000000000000000000047.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000059.tlbin:system/app/mcRegistry/ffffffff000000000000000000000059.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffff000000000000000000000060.tlbin:system/app/mcRegistry/ffffffff000000000000000000000060.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000017.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000017.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/ffffffffd0000000000000000000001a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000001a.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/fffffffff0000000000000000000001b.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001b.tlbin \
    vendor/samsung/dream-common/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/dream-common/proprietary/bin/cbd:system/bin/cbd \
    vendor/samsung/dream-common/proprietary/etc/firmware/cs47l92-dsp1-dsd-176.4kHz.wmfw:system/etc/firmware/cs47l92-dsp1-dsd-176.4kHz.wmfw \
    vendor/samsung/dream-common/proprietary/etc/firmware/cs47l92-dsp1-dsd-352.8kHz.wmfw:system/etc/firmware/cs47l92-dsp1-dsd-352.8kHz.wmfw \
    vendor/samsung/dream-common/proprietary/etc/firmware/cs47l92-dsp1-trace.wmfw:system/etc/firmware/cs47l92-dsp1-trace.wmfw \
    vendor/samsung/dream-common/proprietary/etc/nfc/SGP/sec_s3nrn82_rfreg.bin:system/etc/nfc/SGP/sec_s3nrn82_rfreg.bin \
    vendor/samsung/dream-common/proprietary/etc/nfc/sec_s3nrn82_rfreg.bin:system/etc/nfc/sec_s3nrn82_rfreg.bin \
    vendor/samsung/dream-common/proprietary/etc/somxreg.conf:system/etc/somxreg.conf \
    vendor/samsung/dream-common/proprietary/lib/android.hidl.base@1.0.so:system/lib/android.hidl.base@1.0.so \
    vendor/samsung/dream-common/proprietary/lib/hw/camera.universal8895.so:system/lib/hw/camera.universal8895.so \
    vendor/samsung/dream-common/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/dream-common/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/dream-common/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/dream-common/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/dream-common/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/dream-common/proprietary/lib/libprotobuf-cpp-lite.so:system/lib/libprotobuf-cpp-lite.so \
    vendor/samsung/dream-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/dream-common/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.VP9.Decoder.so:system/lib/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib64/android.hidl.base@1.0.so:system/lib64/android.hidl.base@1.0.so \
    vendor/samsung/dream-common/proprietary/lib64/hw/camera.universal8895.so:system/lib64/hw/camera.universal8895.so \
    vendor/samsung/dream-common/proprietary/lib64/libexynoscamera.so:system/lib64/libexynoscamera.so \
    vendor/samsung/dream-common/proprietary/lib64/libexynoscamera3.so:system/lib64/libexynoscamera3.so \
    vendor/samsung/dream-common/proprietary/lib64/libfloatingfeature.so:system/lib64/libfloatingfeature.so \
    vendor/samsung/dream-common/proprietary/lib64/libhwjpeg.so:system/lib64/libhwjpeg.so \
    vendor/samsung/dream-common/proprietary/lib64/libprotobuf-cpp-full-rtti.so:system/lib64/libprotobuf-cpp-full-rtti.so \
    vendor/samsung/dream-common/proprietary/lib64/libprotobuf-cpp-full.so:system/lib64/libprotobuf-cpp-full.so \
    vendor/samsung/dream-common/proprietary/lib64/libprotobuf-cpp-lite.so:system/lib64/libprotobuf-cpp-lite.so \
    vendor/samsung/dream-common/proprietary/lib64/libsecnativefeature.so:system/lib64/libsecnativefeature.so \
    vendor/samsung/dream-common/proprietary/lib64/libsensorlistener.so:system/lib64/libsensorlistener.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Encoder.so:system/lib64/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.VP9.Decoder.so:system/lib64/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin:system/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000014.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/dream-common/proprietary/vendor/bin/hw/gpsd:system/vendor/bin/hw/gpsd \
    vendor/samsung/dream-common/proprietary/vendor/bin/mcDriverDaemon:system/vendor/bin/mcDriverDaemon \
    vendor/samsung/dream-common/proprietary/vendor/etc/gnss/gps.cer:system/vendor/etc/gnss/gps.cer \
    vendor/samsung/dream-common/proprietary/vendor/etc/gnss/gps.xml:system/vendor/etc/gnss/gps.xml \
    vendor/samsung/dream-common/proprietary/vendor/etc/plmn_delta.bin:system/vendor/etc/plmn_delta.bin \
    vendor/samsung/dream-common/proprietary/vendor/etc/plmn_delta_attaio.bin:system/vendor/etc/plmn_delta_attaio.bin \
    vendor/samsung/dream-common/proprietary/vendor/etc/plmn_delta_usacdma.bin:system/vendor/etc/plmn_delta_usacdma.bin \
    vendor/samsung/dream-common/proprietary/vendor/etc/plmn_delta_usagsm.bin:system/vendor/etc/plmn_delta_usagsm.bin \
    vendor/samsung/dream-common/proprietary/vendor/etc/plmn_se13.bin:system/vendor/etc/plmn_se13.bin \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/.clminfo:system/vendor/etc/wifi/.clminfo \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/bcmdhd_clm.blob:system/vendor/etc/wifi/bcmdhd_clm.blob \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin_b0:system/vendor/etc/wifi/bcmdhd_mfg.bin_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin_b2:system/vendor/etc/wifi/bcmdhd_mfg.bin_b2 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/bcmdhd_sta.bin_b0:system/vendor/etc/wifi/bcmdhd_sta.bin_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/bcmdhd_sta.bin_b2:system/vendor/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt:system/vendor/etc/wifi/nvram.txt \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_a0:system/vendor/etc/wifi/nvram.txt_a0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_a0_ePA:system/vendor/etc/wifi/nvram.txt_a0_ePA \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_murata_r012_a1:system/vendor/etc/wifi/nvram.txt_murata_r012_a1 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_murata_r013_b0:system/vendor/etc/wifi/nvram.txt_murata_r013_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_murata_r014_b0:system/vendor/etc/wifi/nvram.txt_murata_r014_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_murata_r020_b0:system/vendor/etc/wifi/nvram.txt_murata_r020_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_murata_r033_b0:system/vendor/etc/wifi/nvram.txt_murata_r033_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_r01a_a1:system/vendor/etc/wifi/nvram.txt_r01a_a1 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_r01d_b0:system/vendor/etc/wifi/nvram.txt_r01d_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_r01f_b0:system/vendor/etc/wifi/nvram.txt_r01f_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_r01i_b0:system/vendor/etc/wifi/nvram.txt_r01i_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_r02a_a1:system/vendor/etc/wifi/nvram.txt_r02a_a1 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_r02c_a1:system/vendor/etc/wifi/nvram.txt_r02c_a1 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_r02g_b0:system/vendor/etc/wifi/nvram.txt_r02g_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/nvram.txt_r02j_b0:system/vendor/etc/wifi/nvram.txt_r02j_b0 \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:system/vendor/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/wldu.conf:system/vendor/etc/wifi/wldu.conf \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/wpa_supplicant.conf:system/vendor/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/dream-common/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:system/vendor/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/dream-common/proprietary/vendor/firmware/APBargeIn_AUDIO_SLSI.bin:system/vendor/firmware/APBargeIn_AUDIO_SLSI.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/APBiBF_AUDIO_SLSI.bin:system/vendor/firmware/APBiBF_AUDIO_SLSI.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:system/vendor/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/SoundBoosterParam.bin:system/vendor/firmware/SoundBoosterParam.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/bcm4361B0_V0272.0318_murata.hcd:system/vendor/firmware/bcm4361B0_V0272.0318_murata.hcd \
    vendor/samsung/dream-common/proprietary/vendor/firmware/bcm4361B0_V0272.0320_semco.hcd:system/vendor/firmware/bcm4361B0_V0272.0320_semco.hcd \
    vendor/samsung/dream-common/proprietary/vendor/firmware/calliope_dram.bin:system/vendor/firmware/calliope_dram.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/calliope_iva.bin:system/vendor/firmware/calliope_iva.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/calliope_sram.bin:system/vendor/firmware/calliope_sram.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/companion_2l2_master_setfile.bin:system/vendor/firmware/companion_2l2_master_setfile.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/companion_2l2_mode_setfile.bin:system/vendor/firmware/companion_2l2_mode_setfile.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/companion_fw_2l2_3h1.bin:system/vendor/firmware/companion_fw_2l2_3h1.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/companion_fw_2l2_imx320.bin:system/vendor/firmware/companion_fw_2l2_imx320.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/companion_fw_imx333_3h1.bin:system/vendor/firmware/companion_fw_imx333_3h1.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/companion_fw_imx333_imx320.bin:system/vendor/firmware/companion_fw_imx333_imx320.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/companion_imx333_master_setfile.bin:system/vendor/firmware/companion_imx333_master_setfile.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/companion_imx333_mode_setfile.bin:system/vendor/firmware/companion_imx333_mode_setfile.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/dsm.bin:system/vendor/firmware/dsm.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/dsm_tune.bin:system/vendor/firmware/dsm_tune.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/fimc_is_rta_2l2_3h1.bin:system/vendor/firmware/fimc_is_rta_2l2_3h1.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/fimc_is_rta_2l2_imx320.bin:system/vendor/firmware/fimc_is_rta_2l2_imx320.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/fimc_is_rta_imx333_3h1.bin:system/vendor/firmware/fimc_is_rta_imx333_3h1.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/fimc_is_rta_imx333_imx320.bin:system/vendor/firmware/fimc_is_rta_imx333_imx320.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/iva10_rt-kangchen.bin:system/vendor/firmware/iva10_rt-kangchen.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/nfc/sec_s3nrn82_firmware.bin:system/vendor/firmware/nfc/sec_s3nrn82_firmware.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/ois_fw_dom.bin:system/vendor/firmware/ois_fw_dom.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/ois_fw_sec.bin:system/vendor/firmware/ois_fw_sec.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/score_fw_dmb0.bin:system/vendor/firmware/score_fw_dmb0.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/score_fw_dmb1.bin:system/vendor/firmware/score_fw_dmb1.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/score_fw_pmw0.bin:system/vendor/firmware/score_fw_pmw0.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/score_fw_pmw1.bin:system/vendor/firmware/score_fw_pmw1.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/setfile_2l2.bin:system/vendor/firmware/setfile_2l2.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/setfile_3h1.bin:system/vendor/firmware/setfile_3h1.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/setfile_imx320.bin:system/vendor/firmware/setfile_imx320.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/setfile_imx333.bin:system/vendor/firmware/setfile_imx333.bin \
    vendor/samsung/dream-common/proprietary/vendor/firmware/vts.bin:system/vendor/firmware/vts.bin \
    vendor/samsung/dream-common/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/hw/power.universal8895.so:system/vendor/lib/hw/power.universal8895.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/hw/thermal.universal8895.so:system/vendor/lib/hw/thermal.universal8895.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libMcClient.so:system/vendor/lib/libMcClient.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libMcRegistry.so:system/vendor/lib/libMcRegistry.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libbauthtzcommon.so:system/vendor/lib/libbauthtzcommon.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libegis_fp_normal_sensor_test.so:system/vendor/lib/libegis_fp_normal_sensor_test.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libsec-ril.so:system/vendor/lib/libsec-ril.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libsynaFpSensorTestNwd.so:system/vendor/lib/libsynaFpSensorTestNwd.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libuniapi.so:system/vendor/lib/libuniapi.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libuniplugin.so:system/vendor/lib/libuniplugin.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/libwrappergps.so:system/vendor/lib/libwrappergps.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/sensors.bio.so:system/vendor/lib/sensors.bio.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/sensors.grip.so:system/vendor/lib/sensors.grip.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/sensors.sensorhub.so:system/vendor/lib/sensors.sensorhub.so \
    vendor/samsung/dream-common/proprietary/vendor/lib/vendor.samsung.hardware.radio@1.0.so:system/vendor/lib/vendor.samsung.hardware.radio@1.0.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/egl/libGLES_mali.so:system/vendor/lib64/egl/libGLES_mali.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/hw/gps.default.so:system/vendor/lib64/hw/gps.default.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/hw/keystore.mdfpp.so:system/vendor/lib64/hw/keystore.mdfpp.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/hw/nfc_nci.default.so:system/vendor/lib64/hw/nfc_nci.default.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/hw/power.universal8895.so:system/vendor/lib64/hw/power.universal8895.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/hw/thermal.universal8895.so:system/vendor/lib64/hw/thermal.universal8895.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libMcClient.so:system/vendor/lib64/libMcClient.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libMcRegistry.so:system/vendor/lib64/libMcRegistry.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libbauthserver.so:system/vendor/lib64/libbauthserver.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libbauthtzcommon.so:system/vendor/lib64/libbauthtzcommon.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libbt-vendor.so:system/vendor/lib64/libbt-vendor.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libegis_fp_normal_sensor_test.so:system/vendor/lib64/libegis_fp_normal_sensor_test.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libsec-ril.so:system/vendor/lib64/libsec-ril.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libsynaFpSensorTestNwd.so:system/vendor/lib64/libsynaFpSensorTestNwd.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libuniapi.so:system/vendor/lib64/libuniapi.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libuniplugin.so:system/vendor/lib64/libuniplugin.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/libwrappergps.so:system/vendor/lib64/libwrappergps.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/sensors.bio.so:system/vendor/lib64/sensors.bio.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/sensors.grip.so:system/vendor/lib64/sensors.grip.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/sensors.sensorhub.so:system/vendor/lib64/sensors.sensorhub.so \
    vendor/samsung/dream-common/proprietary/vendor/lib64/vendor.samsung.hardware.radio@1.0.so:system/vendor/lib64/vendor.samsung.hardware.radio@1.0.so

ifeq ($(WITH_EXYNOS_BSP),)
PRODUCT_COPY_FILES += \
    vendor/samsung/dream-common/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/dream-common/proprietary/lib/hw/hwcomposer.exynos5.so:system/lib/hw/hwcomposer.exynos5.so \
    vendor/samsung/dream-common/proprietary/lib/hw/memtrack.exynos5.so:system/lib/hw/memtrack.exynos5.so \
#    vendor/samsung/dream-common/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
#    vendor/samsung/dream-common/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/dream-common/proprietary/lib/libcsc.so:system/lib/libcsc.so \
    vendor/samsung/dream-common/proprietary/lib/libdisplay.so:system/lib/libdisplay.so \
    vendor/samsung/dream-common/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
    vendor/samsung/dream-common/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
    vendor/samsung/dream-common/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/dream-common/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/dream-common/proprietary/lib/libfimg.so:system/lib/libfimg.so \
    vendor/samsung/dream-common/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/dream-common/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
    vendor/samsung/dream-common/proprietary/lib/libmpp.so:system/lib/libmpp.so \
    vendor/samsung/dream-common/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.MPEG2.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG2.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib/omx/libOMX.Exynos.VP9.Decoder.so:system/lib/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib64/hw/gralloc.exynos5.so:system/lib64/hw/gralloc.exynos5.so \
    vendor/samsung/dream-common/proprietary/lib64/hw/hwcomposer.exynos5.so:system/lib64/hw/hwcomposer.exynos5.so \
    vendor/samsung/dream-common/proprietary/lib64/hw/memtrack.exynos5.so:system/lib64/hw/memtrack.exynos5.so \
#    vendor/samsung/dream-common/proprietary/lib64/libExynosOMX_Core.so:system/lib64/libExynosOMX_Core.so \
#    vendor/samsung/dream-common/proprietary/lib64/libExynosOMX_Resourcemanager.so:system/lib64/libExynosOMX_Resourcemanager.so \
    vendor/samsung/dream-common/proprietary/lib64/libcsc.so:system/lib64/libcsc.so \
    vendor/samsung/dream-common/proprietary/lib64/libdisplay.so:system/lib64/libdisplay.so \
    vendor/samsung/dream-common/proprietary/lib64/libexynosgscaler.so:system/lib64/libexynosgscaler.so \
    vendor/samsung/dream-common/proprietary/lib64/libexynosscaler.so:system/lib64/libexynosscaler.so \
    vendor/samsung/dream-common/proprietary/lib64/libexynosutils.so:system/lib64/libexynosutils.so \
    vendor/samsung/dream-common/proprietary/lib64/libexynosv4l2.so:system/lib64/libexynosv4l2.so \
    vendor/samsung/dream-common/proprietary/lib64/libfimg.so:system/lib64/libfimg.so \
    vendor/samsung/dream-common/proprietary/lib64/libhdmi.so:system/lib64/libhdmi.so \
    vendor/samsung/dream-common/proprietary/lib64/libhwcutils.so:system/lib64/libhwcutils.so \
    vendor/samsung/dream-common/proprietary/lib64/libmpp.so:system/lib64/libmpp.so \
    vendor/samsung/dream-common/proprietary/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Decoder.so:system/lib64/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Encoder.so:system/lib64/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.MPEG2.Decoder.so:system/lib64/omx/libOMX.Exynos.MPEG2.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/dream-common/proprietary/lib64/omx/libOMX.Exynos.VP9.Decoder.so:system/lib64/omx/libOMX.Exynos.VP9.Decoder.so
endif

# Create Mali links for Vulkan and OpenCL
PRODUCT_PACKAGES += libGLES_mali

